name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: Checkout sources
      - uses: actions/setup-node@v1
        name: Setup node
        with:
          node-version: "10.x"
      - run: npm install --global neon-cli
        name: Install neon
      - run: neon version
        name: Print neon version
      - run: neon build --release
        name: Execute build
      - run: node lib/index.js
        name: Run simple smoke test
